version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: concert_mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: concert_user
      MONGO_INITDB_ROOT_PASSWORD: concert_pass
      MONGO_INITDB_DATABASE: concert_db
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: concert_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: concert_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data:
  redis_data: